//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradysProperties {
    
    
    public partial class OKC_Properties {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new BradysProperties.RegionalProperties Master {
            get {
                return ((BradysProperties.RegionalProperties)(base.Master));
            }
        }
    }
}
