//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradysProperties.PropertyListings.NormanProperties {
    
    
    public partial class MasonPlaza {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new BradysProperties.PropertyMaster Master {
            get {
                return ((BradysProperties.PropertyMaster)(base.Master));
            }
        }
    }
}
